//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class buyitemdetailtbl
    {
        public int bid { get; set; }
        public int pid { get; set; }
        public int pqty { get; set; }
        public int pprice { get; set; }
        public string mid { get; set; }
        public System.DateTime btime { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<int> payid { get; set; }
    }
}
