//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class note
    {
        public int n_id { get; set; }
        public Nullable<double> videotime { get; set; }
        public Nullable<int> p_id { get; set; }
        public string mid { get; set; }
        public string n_content { get; set; }
        public string n_title { get; set; }
        public string create_time { get; set; }
        public Nullable<int> n_grade { get; set; }
        public string p_name { get; set; }
    }
}
