//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFDBLibrary
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class producttbl
    {
        public int pid { get; set; }
        public Nullable<int> kind { get; set; }
        public Nullable<int> category { get; set; }
        public string mid { get; set; }
        [Display(Name = "名稱")]
        public string name { get; set; }
        [Display(Name = "介紹")]
        public string intro { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> score { get; set; }
        [Display(Name = "圖片")]
        public byte[] picture { get; set; }
        public string vidiourl { get; set; }
    }
}
